### ISSUE TITLE
Overall process including application lifecycle

### ISSUE THREAD

**Issue by SandraArps** [rht-labs/enablement-docs#121]
To better understand the process from a non technical / developer view:

The Big Picture is an emerging view of how CI/CD infrastructure grows during a residency (and we plan to emulate that on the 4 day enablement session) but we could do something similar with practices.

e.g. Every residency starts with Priority Sliders -> Social Contract -> Target Outcomes
If the residency is greenfied we tend to do Event Storming.
If the residency is brownfield, we tend to do Metric Based Process Mapping.
Whichever above is selected, we tend to then do User Story Mapping / Value Slicing and build a product backlog.
We then, again, have one of two tracks to follow - either Scrum or Kanban.

**Comment by springdo** [comment]
I think this is done via the Practice Corner. Feel free to re-open if you don't think so!
