### ISSUE TITLE
Trunk based development

### ISSUE THREAD

**Issue by tenfourty** [rht-labs/enablement-docs#123]
It would be great if we could integrate and teach a strong opinion on trunk based development.

It's strongly advocated by Jez Humble in his books, it's been shown the state of DevOps report research to have a very high correlation to high performing teams and it's a pre-requisite for CD.

Here is a recent article on this - CI and Feature Branching - http://www.davefarley.net/?p=247

Also [Jez Humble's tweet storm on this](https://twitter.com/jezhumble/status/982988370942025728), in which @InfoSec812 also was involved in the conversation. You can also read the unrolled version [here](https://threadreaderapp.com/thread/982988370942025728.html)

His key points:

> I personally believe it comes down to this: trunk-based development is all about communication. We're using version control to communicate what we're doing to the rest of the team. To do it regularly enough, we have to work in very small batches.

> When people get super mad about things (including me), I tend to look for something cultural or identity-related which is the source of the emotion. Trunk-based development is about putting the needs of the team above the needs of individual.

> The premise of CI and trunk-based development is that coding is fundamentally a social, team activity. This presents a challenge to the mythos of the developer-as-hero which is still pervasive in our industry.

> Thus my hypothesis about why feature branching vs CI / TBD is such a hot button issue: we are striking at one of the central beliefs about what it means to be a "good" programmer. There's also the fact that people aren't trained to work in small batches and find it uncomfortable.

These are powerful points - and as we are already bought into delivering small batches of work in what we do I think it's important that this enablement also teaches this principle out of the gate.

I've tagged this issue as an enhancement request and also I do think that we need CoP alignment so I've tagged it with that as well.

CC @springdo @sherl0cks for this issue

**Comment by springdo** [comment]
closing in favour of the proposed GIT exercise https://github.com/rht-labs/enablement-docs/issues/347
