### ISSUE TITLE
Resolve Gitlab increased privileges (SCC)

### ISSUE THREAD

**Issue by acammies** [rht-labs/enablement-docs#132]
- [ ]  Talk to Mak about options
- [ ]  Agree as a team globally on direction
- [ ]  Top & Tail content

**Comment by makentenza** [comment]
Discuss if 1 GitLab for the whole Cluster could work. There is not a quick solution right now to run GitLab container as non-root user, that would require hacking the actual GitLab container from Omnibus

**Comment by springdo** [comment]
@sherl0cks  - will probs agree. Maybe we get one G-Lab for the whole course in May. We can then keep the instructions in, incase people want to know how to do this stuff themselves. They can then be marked not as part of the critical path.

**Comment by sherl0cks** [comment]
@springdo that sounds fine to me. thanks working towards an aligned solution here.

**Comment by springdo** [comment]
https://github.com/rht-labs/enablement-docs/pull/145 - this should cover off this one. I've moved the section and added a heading to say it's optional

**Comment by makentenza** [comment]
Closed by #145
