### ISSUE TITLE
Enable the enablement to be run out from a training session

### ISSUE THREAD

**Issue by makentenza** [rht-labs/enablement-docs#134]
As part of the `https://github.com/rht-labs/enablement-docs/tree/master/exercises/0-rogue-cluster` exercise, we should add instructions and requirements in case anyone could run this on their own using a lightweight cluster like `minishift` or the `CDK`

**Comment by springdo** [comment]
@makentenza - happy for you to try run this on Minishift and e2e test it. I will assign this task to you so! 🏅

**Comment by springdo** [comment]
Hi @makentenza! I think our preferred direction to take with the course is to do it in Code Ready work space negating the need for any local setup.  Closing it but please re-open if you feel strongly against that
