### ISSUE TITLE
CI / CD for the labs content

### ISSUE THREAD

**Issue by springdo** [rht-labs/enablement-docs#14]
Create CI / CD for labs content (slides, doc sites etc)

**Comment by sherl0cks** [comment]
@springdo give our needs and time lines, can we make this lower priority? . We can operate with pure markdown read locally or from github just fine.

**Comment by springdo** [comment]
Yeah @sherl0cks , I completely agree. This was captured and de prioritised almost immediately! Have a look in the slicing map we did, you should see it at the bottom

**Comment by springdo** [comment]
https://github.com/rht-labs/enablement-docs/blob/master/kick-off/value-slice-map.jpg
