### ISSUE TITLE
Alignment on Tagging Strategy

### ISSUE THREAD

**Issue by tdbeattie** [rht-labs/enablement-docs#160]

**Comment by springdo** [comment]
Got something in the diary for this tomorrow!

**Comment by sherl0cks** [comment]
Per today's convo, I don't think its critical we bottom this out for the first enablement run, as it's simply too much change to introduce at this time, and we really don't have a solution we all agree to at this point. But we really should work towards updating this approach on the second pass. Also, there are many others outside of Labs that need this type of thing.

**Comment by springdo** [comment]
Suggestion that we move this disccussion to the labs-ci-cd repo,
