### ISSUE TITLE
Setup OpenShift Cluster for May 2018 Event

### ISSUE THREAD

**Issue by springdo** [rht-labs/enablement-docs#17]
Need two clusters (maybe could reuse them?) @makentenza and @oybed can you get me a 3.9 cluster to be able work in for building the content and testing it please?

**Comment by sherl0cks** [comment]
I have shared the latest sandbox cluster with @springdo. Renaming to reflect the need for the actual event.

**Comment by springdo** [comment]
This cluster will probs be a MEGA_CLUSTER ! If we have 24 delegates each with 3  project namespace and 3 * each of GitLab, Nexus, Jenkins, Mongodb and some apps ...... this could be a big one! 

@makentenza  / @oybed  / @logandonley   - not sure when yous are planning to build this sucker but maybe we should sync before hand to give yous an idea of capacity? Also; Im guessing @mtakane  might know the list of people attending V1 of course to be added to the ol' LDAPers

**Comment by sherl0cks** [comment]
@springdo it may make sense to centralize gitlab and nexus and have folks only focus on their app. gitlab operations isn't something attendees need to know how to manage

**Comment by springdo** [comment]
@logandonley  - any word on how the cluster is coming along? We want to start end to end testing this puppy on Monday; be good if we had the actual cluster and you create me, tim and a few others new ids in the same group the learners will be using.

**Comment by tdbeattie** [comment]
That's great. Thanks @logandonley 

We'd like to run some testing from tomorrow on this so would be great if you or @makentenza could create users for me, @acammies, @robbbbh, @springdo and Stuart Winchester. Thanks!

**Comment by oybed** [comment]
@tdbeattie due to TZ, I think your tomorrow will not work, but it will most likely be available Tuesday your TZ. 

Also, @tdbeattie make sure to add the users you want to have enabled in the data gathering sheet (I'll link you in the sheet in case you don't have it handy)
