### ISSUE TITLE
Setup the Slides template 

### ISSUE THREAD

**Issue by springdo** [rht-labs/enablement-docs#18]

**Comment by sherl0cks** [comment]
would like to understand why we cannot use either slides.com or google docs resources we already have, so we can focus energy on the actual content

**Comment by springdo** [comment]
@sherl0cks  - we can; and might have to depending on how much time we have! Having things on our own revealJs template and not just on slides.com means we can version control etc. Google slides might be the quickest solution though given skills time etc.
I have created a (reveal theme)[https://github.com/rht-labs/slides-template] and popped it into our reops. It has things like our Labs and RH logos pinned to the corners and the RH colour scheme too

**Comment by sherl0cks** [comment]
@springdo ok. I worry about maintenance here, but I'll drop this for now
