### ISSUE TITLE
Exercise 1 - The Manual Menace

### ISSUE THREAD

**Issue by springdo** [rht-labs/enablement-docs#2]
## Technical Lab 
During this lab, delegates will build out and update their OCP cluster environment using code. They will ultimately create a lightweight version of the CI/CD repo but start from nothing but an empty Ansible Inventory.  
## Ideas for the Lab flow:
* Intro to the OCP Env, Ansible and Container basics (this might be assumed already known but should have basic overview of the things ready for learners)
* Check people can login / access the cluster etc
* Use Ansible to provision the Project Namespaces used in the rest of the labs (OpenShift Applier)
* Use Ansible (OpenShift Applier) to add group permissions 
* Add Jenkins, persistent using an S2I for additional Config
* Add plugins to S2I eg green balls and junit reporter
* Add a Jenkins Slave (here or in the next lab?)
* Add GitLab (or Gogs) and Nexus using the OpenShift Applier and add your faces game avatar to it. 
* Create HELLO WORLD in git and add to Jenkins 
## ADVANCED / XTRA TOPICS
* Add SSL to endpoints
* Sonar Qube?
* Add Mattermost or something similar to the PBI

**Comment by oybed** [comment]
@springdo Can we call this "Exercise 1 - Labs CI/CD" instead of using the PBI term. Based on the content, it really just seems to cover the Labs CI/CD portion - not the entire "PBI".

@sherl0cks FYI

**Comment by springdo** [comment]
Sure we can remove PBI aspect but we need to keep on theme with the Star Wars content. We could call it  `The Infrastructure Menace`

**Comment by oybed** [comment]
@springdo well, this isn't `infrastructure` per-say - that was my point before.

**Comment by springdo** [comment]
Yeah I get that it is not true `infra` but the context / preface of the lab will be about how _traditionally_ infra was a problem and how using infra as code / config as code to be able to repeatably create environments and git servers etc is very powerful.

**Comment by sherl0cks** [comment]
I would suggest "the manual menace" or the "snowflake menace".

I'm a bit iffy on the value of having people recreate labs CI/CD - you're looking at 3ish days of tech content. This is gonna take some time for folks to grok.

CoP stuff to align on:
- how we create namespaces. it's being discussed moving away from having devs create/delete shared project namespaces as most customer envs will not allow this, so the skill is not transferable.

**Comment by springdo** [comment]
Yeah @sherl0cks,  I can change it to the Manual Menace that's fine. @tdbeattie, what do you think? 

I think we're a bit off on the level of the ci/cd content they would create. Idea here is you're giving them a very guided tour through the core of the ci/cd project. We'll provide templates etc and learner will just add in the parameters and add the item to the inventory as they go. This will allow them build up a _ci/cd light_ over the course of the  first part. By doing this they are exposed to some of the magic that's in the box at a consumable level. We cannot just hand over thr labs ci/cd project and say "go" as people don't learn that way. The idea was at the end of the course after the learners have been through creating some of the components we show them the whole ci/cd project

As for the namespace creation, so far all of our clusters we have been in control of as we provision them for our clients do access has not been an issue. In the world of doing DevOps I would hesitate to remove the ability for the dev to not be able to op the cluster!

**Comment by tdbeattie** [comment]
Just to give a bit of background. I actually initially suggested using "PBI" in the first exercise title. My thinking at the time was I'd like the exercises to start with PBI and finish with Demo Day to align to residency format (and we thought we might run sprints inbetween). The sprint idea is proving too tricky (at least for this first run) and, following the chat here and on RocketChat, I now completely agree PBI is not the right term to use. 

I actually prefer "The Manual Menace" - we're coming from a world of manual pain (in everything.... infrastructure, provisioning, building, testing, releasing, etc.) and this exercise starts to take us down the path of automating everything and the mindset of 'everything as code'.

**Comment by springdo** [comment]
@sherl0cks, @makentenza @oybed  - from call we discussed destroying the `dev` and `test` environments and recreating them at the end of each lab to get people into the habit of full phoenix server!

**Comment by sherl0cks** [comment]
Just to clarify @springdo we want to destroy the contents of `dev` and `test`, but we do not want to delete the projects themselves, which we'll manage in a different inventory with its own lifecycle.

**Comment by springdo** [comment]
Closing now as only one task to extend lesson 1
