### ISSUE TITLE
Joining Instructions 

### ISSUE THREAD

**Issue by springdo** [rht-labs/enablement-docs#20]
Create the joining instructions and mail them to delegates. 
This can be used as a starter for now.

## Required prerequisites :
* Passionate about doing DevOps and Agile software development 
* Lean Startup mentality for working in small teams to build great applications quickly and iteratively
* Open minded attitude
* Willingness to roll up your sleeves to get your hands dirty doing labs
* Willingness to learn and work together as part of a team
* Familiarity with concepts of OpenShift, Containers and Ansible
* Complete the git 101 tut (https://try.github.io/)

## Machine requirements: 
* OpenShift CLI installed (v3.9)
* Ansible Installed (v2.5)
* NodeJs >v8 
* Docker
* A good text editor such as VSCode / Atom / IntelliJ with some handy support plugins installed
* * Yaml
* * Docker
* * Ansible
* * VueJS
* * NodeJS
* * Groovy

## Nice to have but not essential for enablement
* Hands-on experience with OpenShift 3.x
* Familiarity with automation tooling such as Ansible
* Familiarity with Jenkins
* Scrum or other Agile Frameworks

**Comment by sherl0cks** [comment]
@springdo regarding machine requirements, I think we should only require docker and then ship folks something like https://github.com/rht-labs/labs-ci-cd/tree/master/docker/tool-box

**Comment by springdo** [comment]
@sherl0cks sounds good to me! Is the tool box available on docker hub already for people to pull? If not, is this something you can work on? Maybe if you push something just tag a specific version for the enablement material. Oh I see ansible 2.5 is out already!

**Comment by sherl0cks** [comment]
I'll setup builds for the tool-box and then add a new build your above requirements (looks like node 8 is the only new artifact). Where should that build live? I see a few different repos
