### ISSUE TITLE
Confusing info on the automatic email to change IdM user's passwords

### ISSUE THREAD

**Issue by makentenza** [rht-labs/enablement-docs#230]
We have many students saying that they get confused by the email message they got to change their password. This confusion is related to the error message they got about 'home directory' but the most important one is that they think they need to work from the host they have connected to change the password. We need to add some clarification in the meantime the self service url for password changing is not available.

**Comment by oybed** [comment]
@springdo this is already fully automated with Ansible. Also, we should **not** use very plain/simple passwords as these systems are on the public internet (and we've seen bad results from "simple" passwords before).

**Comment by springdo** [comment]
@oybed  yeah but the scope and longevity of the password is minimal. People will be cloning publicly available content; which they do without password anyway and then creating content in OCP land which will probs at most last for 10 days before deletion.

**Comment by springdo** [comment]
closing as we don't use this mechanism anymore
