### ISSUE TITLE
Add oc tag & label commands from first lab to the applier's inventory

### ISSUE THREAD

**Issue by springdo** [rht-labs/enablement-docs#236]
Currently there is a dirty hack to move the slave into the users ci-cd namespace. This is not done as part of the applier and should be as when they burn their projects to the ground it doesn't get recreated. 

Fix this by adding to the `inventory` and running via the oc tag and oc label using `openshift-applier`. @oybed can probs help out whoever ( or @Tompage1994) takes on this task

**Comment by oybed** [comment]
Labels can easily be handled as a post-step in the `openshift-applier` inventory by utilizing the `openshift-labels` role:
https://github.com/redhat-cop/openshift-applier/tree/master/roles/openshift-labels

**Comment by springdo** [comment]
I knew we could do labels; but can we do tags also? 
Basically we need to `openshift-applier-ify` these 3 commands!

```bash
oc project <YOUR_NAME>-ci-cd
oc tag openshift/jenkins-slave-npm:latest jenkins-slave-npm:latest
oc label is jenkins-slave-npm role=jenkins-slave
```

**Comment by oybed** [comment]
We don't have a role for tags, but this seems like a great opportunity to model one after the existing one for labels - maybe even make that one a bit more generic and work for both (if it make sense)

**Comment by springdo** [comment]
Is that you assigning yourself some work there @oybed?? Sounds good to me! ;)

**Comment by gsampaio-rh** [comment]
PR https://github.com/rht-labs/enablement-ci-cd/pull/33
