### ISSUE TITLE
Update exercises to not use peoples passwords

### ISSUE THREAD

**Issue by oybed** [rht-labs/enablement-docs#242]
We need to update the exercises to avoid telling people to store their passwords in plain text.

**Comment by springdo** [comment]
Agreed; on previous runs of the course we toyed with the ideas of learners using Dummy accounts to get around this and told people to use simple passwords ie not their Red Hat ones!! 

Happy for you to PR this though; Ill assign you the task if you're up for it.

**Comment by springdo** [comment]
closing as we now use pre-canned user credentials
