### ISSUE TITLE
Update material to not reference a "fixed" hosting environment

### ISSUE THREAD

**Issue by oybed** [rht-labs/enablement-docs#243]
The material should be written in such a way that the hosting environment info can be published as part of a session (i.e.: one-page hand-out/info on the whiteboard, etc.) and not be part of the main course material.

**Comment by oybed** [comment]
I believe this issue has been addressed in the latest version of the material.

**Comment by tylerauerbeck** [comment]
I think this is okay to close. @springdo @oybed thoughts?

**Comment by oybed** [comment]
Yup - closing
