### ISSUE TITLE
Create UI/UX Exercise 

### ISSUE THREAD

**Issue by springdo** [rht-labs/enablement-docs#244]
Currently we have no UI/UX in the Enablement. A natural evolution would be to add some UI/UX practices, depending on Length of these exercise, other ones might need to be trimmed or course length extended

**Comment by pcarney8** [comment]
Highly recommend the Screenflow workshop that Riley did

**Comment by rdebeasi** [comment]
Here's the screenflow/UI design workshop: https://openpracticelibrary.com/practice/ui-design-workshop/

Here's the Lean UX workshop that we ran at the last couple of DO500 runs: https://openpracticelibrary.com/practice/lean-ux-workshop/

**Comment by springdo** [comment]
Closing in favour of recent issue raised by UXy person #359
