### ISSUE TITLE
Create a definition of done

### ISSUE THREAD

**Issue by springdo** [rht-labs/enablement-docs#25]
@tdbeattie - when you get amoment can you uploaad the pic we have on the wall

**Comment by tdbeattie** [comment]
Definition of Done we've come up with and on wall in our Labs is [here](https://github.com/rht-labs/enablement-docs/blob/master/kick-off/definition-of-done.jpg).

A feature (i.e. standalone part of an exercise) is considered done when:
- Infrastructure and code available so learners can successfully complete the exercise
- supporting materials (introductions, wrap ups, etc.) written and reviewwed
- exercises written and formatted consistently with screen shots
- exercises independently tested
- BIG PICTURE updated for the latest part of the exercise
- all source (code, content, apps) should be hosted in rht-labs GitHub
- each course component peer reviewed

An Epic (i.e. full exercise) is considered done when:
- All built artefacts hosted on long lived cluster
- At least one real world lab example is included in the content
- Links to practice library included or PR raised where appropriate
