### ISSUE TITLE
Credential requirement missing from exercise 1, part 7

### ISSUE THREAD

**Issue by jacobsee** [rht-labs/enablement-docs#253]
It should be noted that git credentials need to be supplied using `-e '{"git_credentials": { "GIT_USERNAME": "myname", "GIT_PASSWORD": "mypassword"}}'` when re-applying the Ansible playbooks at the end of the first exercise (Live, Die, Repeat). It is currently missing from the examples, but is required.

**Comment by oybed** [comment]
@jacobsee thanks for pointing this out. As this is "new feature" not part of the official instructions yet, we'll be closing out this issue as the direction forward may be different.
