### ISSUE TITLE
Docs missing ansible parameter in Exercise 1, Part 7, Step 4

### ISSUE THREAD

**Issue by ptforsberg** [rht-labs/enablement-docs#257]
`ansible-playbook apply.yml -i inventory/ -e target=tools` 

is missing 

`-e '{"git_credentials": { "GIT_USERNAME": "<YOUR_NAME>", "GIT_PASSWORD": "<YOUR_PASSWORD>"}}'`

**Comment by oybed** [comment]
@ptforsberg thanks for pointing this out. Please also see comment on #253. This isn't part of the "official" path yet, so closing out for now.
