### ISSUE TITLE
Make content of lab exercises more generic

### ISSUE THREAD

**Issue by rsriniva** [rht-labs/enablement-docs#268]
We (Red Hat Training) are developing a commercial course (DO500) based on the content produced by the open innovation labs. We want to stick as close as possible to the original upstream content and contribute as many changes as possible upstream to avoid divergence

This issue has been created to kick off discussions around how we can work together to make the change request and merge process work smoothly.

To give you an example for the kind of changes we are planning to make and contribute upstream - consider the main landing page at https://rht-labs.github.io/enablement-docs/:

* We are planning to remove the quote "Red Hat Open Innovation Labs Enablement Material. Preparing Engineers, consultants and TSMs with all the cultural and engineering practices for life in a Residency." from under the main "DevOps Culture & Practice" title

* Change or outright remove the paragraph under the jenkins robot. Our course is 5 days in length, for example....

* Make the learner outcomes more generic to match our course offering - the main focus is on paid Red Hat Training customers and not internal Red Hat staff

We have already forked the enablement-docs repo into our own org - is there a preference for how the pull request needs to be done - separate feature branch in our forked repo? or just direct from master?

We plan to make very granular commits so that you can decide which ones to cherry pick for merge into upstream.

**Comment by tenfourty** [comment]
could we use some sort of rendering script that puts in branding to the final generated content?

**Comment by springdo** [comment]
Closing as we now have an agreed flow for keeping DO500 in sync with 'Upstream' DevOps Culture and Practice enablement
