### ISSUE TITLE
Send out Calendar invites for sprint cadence

### ISSUE THREAD

**Issue by springdo** [rht-labs/enablement-docs#27]
We're going to use Scrum and 3 x 1 week sprints to build out this enablement session. 

Proposed Sprint Cadence
- Sprint Planning: Thursdays 1000-1200 (UK time)
- Daily Scrum: Daily 0945-1000 (UK time)
- Sprint Review: Wednesday - 1600-1700 (UK time)
- Sprint Retrospective: Wednesday - 1700-1800 (UK time)

**Comment by tdbeattie** [comment]
All events scheduled.

Will add other stakeholders and interested parties to the Sprint Reviews as they are sent to me.
