### ISSUE TITLE
Have container for attendee computer setup

### ISSUE THREAD

**Issue by mtakane** [rht-labs/enablement-docs#282]
### *** Updated on 11th July 2019 to follow the "standard" issue format ***
**Original text:** want to remove having folks be required to setup their own computers.

**Is your feature request related to a problem? Please describe.**
Using the participants laptops often presents challenges, and at times blockers, related to: incorrect versions, users didn't complete prereqs, no admin rights, variances between the various OS flavors. This issue is to track the elimination of using the participants laptops, and hence avoid requiring the participants to prep/setup their own computers with the prereqs.

**Describe the solution you'd like**
Preferably, we would use a hosted environment to emulate the local working environment that a technical person uses - for example by utilizing a solution like [CodeReady Workspaces](https://developers.redhat.com/products/codeready-workspaces/overview). 

**Describe alternatives you've considered**
A couple of alternatives:
1) A slimmed down set of technical content/exercises may eliminate some of the tech prereqs, but not by much. 
2) Provide pre-provisioned laptops for the class

**Additional context**
Some class participants may not even want to change their local environments as it could "break" their existing setup, or for lesser technical people it may feel like it goes beyond what they need in their day-to-day job and hence "clobbers" up their laptop with additional software needed just for one week.

**Comment by oybed** [comment]
Running the "local" part is always biting *hard*, especially since we now are supporting running Windows. We need to come up with a better/alternative solution to running the local environment ASAP. I.e.: utilizing a container, CodeReady Workspace, etc.

@mtakane @springdo @eformat @mcanoy

**Comment by tylerauerbeck** [comment]
I think we can close this since we've introduced CodeReady workspaces
