### ISSUE TITLE
Exercise 1: add an earlier "git push" check to ensure it's working early on

### ISSUE THREAD

**Issue by oybed** [rht-labs/enablement-docs#298]
Some users can go through much of exercise 1 without knowing that they have issues with their git configuration, etc. etc. (e.g: conflict with existing configuration, incorrectly configured, etc. etc.). Hence it would be good to have an "early check" that their git setup it working as expected without going through much of exercise 1 to find this out.

**Comment by springdo** [comment]
@tylerauerbeck and I think this is not relevant in new world way of doing thangs. The git intro thingy will also help alot of this out so closing in favour of it
