### ISSUE TITLE
Exercise 2 - Attack of the Pipelines

### ISSUE THREAD

**Issue by springdo** [rht-labs/enablement-docs#3]
## Technical Lab
In this lab we will introduce the TODO list app, the backend and try get the walking skeleton of the app up and running, building and deploying through OCP.  This is also where they’ll find their basic ToDoList App already created (in Lab 3, they’re going to add a feature). This plus the first exercise will simulate the full flow of the average first Sprint on a Residency.

## Ideas for the Lab flow:
 * Introduce the TODO List app (vuejs/ nodejs /mongodb)
 * Build and run locally
 * Use Ansible (OpenShift Applier) to add Jenkins Slave?
 * Use Ansible (OpenShift Applier) to add MongoDB for each proj namespace
 * Create (using the UI) a simple BUILD > BAKE > DEPLOY
 *  * <develop> to ‘dev’ env
 *  * <master> to ‘test’ env
 * Add Git hooks for triggering the build in Jenkins
 * Create Pipeline for Backend Microservice(s) also following same build > bake > deploy pattern

## ADVANCED / XTRA TOPICS
 * Use config maps / env vars to inject the DB credentials into the nodejs app
 * Introduce UAT env using ansible and extend <master> branch pipeline with promotion to UAT stage
 * Create complex deployment eg Blue/Green
 * Canary Deployment

**Comment by sherl0cks** [comment]
CoP Stuff to align on:
- what projects we have, stage names and promotion paths

**Comment by sherl0cks** [comment]
IMHO - this is 1 - 1.5 days of content

**Comment by springdo** [comment]
@sherl0cks  - I like the `.openshift-applier` inventory idea. It always annoyed me that the deployed apps was housed with everything else so that's cool.
