### ISSUE TITLE
Day 1 - Material for the first day and other fluffy parts throughout the course

### ISSUE THREAD

**Issue by springdo** [rht-labs/enablement-docs#30]

**Comment by springdo** [comment]
@sherl0cks - we have created a bunch of `Epics` for each exercise and the first bit of the course. Using Zenhub plug in form the browser, these appear with all the linked issues underneath. But ultimately git just creates them as issues. I can add a label to highlight this for ease!

**Comment by sherl0cks** [comment]
we need to https://github.com/rht-labs/enablement-docs/issues/109 so others know about ZenHub
