### ISSUE TITLE
Exercise screenshots need updates

### ISSUE THREAD

**Issue by oybed** [rht-labs/enablement-docs#302]
Most of the exercise screenshots need to be updated with up-to-date info. Some screenshots have been "left-behind" due to other changes, and some are showing names/values that are confusing.

**Comment by springdo** [comment]
Where these have been identified, we should ask attendees to screener them and contrib there and then.

**Comment by oybed** [comment]
That's a good idea ... let's see if we can maybe get some of that done this week (during our session in San Antonio)

**Comment by springdo** [comment]
Marking as closed as we fixed some of these last week and in boston. In future we should raise specific issues for given screeners or fix on the fly
