### ISSUE TITLE
Exercise instructions are confusing re: username

### ISSUE THREAD

**Issue by oybed** [rht-labs/enablement-docs#303]
With the latest runs, where generic user names (labX) are used, the users are at times confused around which username to use for their "YOUR_NAME" replacements. This content needs to be reviewed and updated to be correct/clearer. 

Also, some of us would prefer to use non-generic usernames, so moving back to **not** using `labX` as the username would also help with this issue.

**Comment by springdo** [comment]
@tylerauerbeck and I think the labX stuff has proved to be very useful for debugging specific users and catching people up. Also it helps with the pairing and mobbing by not having one persons id as the name pair. Helps with constant changing roster of attendees also. Think we can close this out as something we won't do.
