### ISSUE TITLE
Exercise instructions should have clickable images

### ISSUE THREAD

**Issue by oybed** [rht-labs/enablement-docs#305]
Users have requested the option to click on an image to get a "bigger" / clearer view of a screenshot.

**Comment by springdo** [comment]
https://desmonding.me/zooming/docs/#/

**Comment by springdo** [comment]
Also this closed PR from some time ago
https://github.com/rht-labs/enablement-docs/pull/222

**Comment by tylerauerbeck** [comment]
This came up again this week, so I think it's definitely worth revisiting.
