### ISSUE TITLE
Exercises 2 - webhook configuration under the "gogs" section, not "general"

### ISSUE THREAD

**Issue by oybed** [rht-labs/enablement-docs#309]
This is in general confusing, but nevertheless needs to be updated to reflect the correct section where it can be found

**Comment by oybed** [comment]
This is in general confusing, but nevertheless needs to be updated to reflect the correct section where it can be found

**Comment by springdo** [comment]
I think the solution here is to remove the gogs plugin as it's a bug in it that makes it appear in this section

**Comment by gsampaio-rh** [comment]
Resolved on https://github.com/rht-labs/enablement-ci-cd/pull/36
