### ISSUE TITLE
Decide on tooling for the content

### ISSUE THREAD

**Issue by springdo** [rht-labs/enablement-docs#31]
For the first pass; we're going to do things using `Docsify` and revealJS.

**Comment by sherl0cks** [comment]
@springdo let's discuss. We have https://redhat.slides.com if we really are set on revealJS.

**Comment by springdo** [comment]
I think there is a separate item for the slides @sherl0cks  - Im going to crack on with Docsify for the moment. everything is written in Markdown so that should be the lowest common denominator anyway!
