### ISSUE TITLE
Merge todolist FE and API 

### ISSUE THREAD

**Issue by springdo** [rht-labs/enablement-docs#316]
As per the discussion we had in January, this would simplify much of the exercise and remove the need for arbitrary copy and paste not central to the learning. I've begun a good bit of this work for the apps in my own repo https://github.com/springdo/todolist and once i've updated the exercises and tested we can look to make the monster merge

**Comment by oybed** [comment]
@springdo glad to hear this ... and it will most likely take care of some of the other open issues at the same time. Please let me know if any assistance is needed with any of this.

**Comment by tylerauerbeck** [comment]
@springdo I think this is in pretty good shape now right?

**Comment by springdo** [comment]
👍 🚀
