### ISSUE TITLE
Create contribution guide and testing approach similar to the one created for OPL

### ISSUE THREAD

**Issue by springdo** [rht-labs/enablement-docs#320]

**Comment by tdbeattie** [comment]
Agreed we need to create a CONTRIBUTING.md file.

As a starter for ten, I would like to suggest we use a similar guide to the one [we put in place for the Open Practice Library](https://github.com/openpracticelibrary/openpracticelibrary/blob/staging/CONTRIBUTING.md). This included the Optimistic Merging Guidelines after a good discussion at https://github.com/openpracticelibrary/openpracticelibrary/issues/208.
