### ISSUE TITLE
Extend pipeline/component visual 

### ISSUE THREAD

**Issue by darachcawley** [rht-labs/enablement-docs#327]
Taking the visual pipeline and component breakdown from the wall and creating a smaller visual per group, so they can tick off which piece they think they completed, as they go through the labs stages. This would give everyone an understanding of which step in the lab, relates to the bigger picture.

**Comment by springdo** [comment]
Thanks for your suggestion @darachcawley - we have implemented the Mini Big Picture as per your suggestion!
