### ISSUE TITLE
Linux setup doesn't work for Debian based systems

### ISSUE THREAD

**Issue by pcarney8** [rht-labs/enablement-docs#337]
*Differences in instructions for exercise setup for Ubuntu 16.04*

These were actually attempted with Ubuntu 16.04, so some steps may not be necessary due to differences in pre-installed packages if using other flavors of Ubuntu

*Ubuntu doesn't allow login as root*
All commands requiring superuser access must be prefixed with `sudo`.
Another alternative is to elevate to a root terminal with `sudo su -`.

*Ubuntu uses apt instead of dnf*
Must replace `dnf` with `apt-get` for software that's already in repo. Otherwise, must use `dpkg -i` to install standalone packages not in repo.

*Package differences*
Package `java-1.8.0-openjdk-devel` does not exist in Ubuntu repositories. Instead, use:
```
sudo apt-get install openjdk-9-jdk
```
(or whatever latest OpenJDK version is; use `apt-cache search openjdk` to find it)

When downloading Chrome, Atom, Visual Studio - grab the Debian/Ubuntu package (.deb) and not the .rpm package.
Install .deb using:
```
sudo dpkg -i <package-file-name>
```
Seen recommendations to run `sudo apt-get install -f` after `dpkg` to fix dependencies.
For Chrome, I just specifically installed `sudo apt-get install fonts-liberation`

On step to install git, ansible, and docker, DO NOT install ansible or docker. Follow the instructions on this site for Ubuntu 16.04

https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-16-04
https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-ansible-on-ubuntu-16-04

The steps to start and enable Docker should not be necessary if following the above instructions. If using a different version of Ubuntu, Google "install docker Ubuntu <version>" or "install ansible Ubuntu <version>".

Had to change version of openshift-applier in requirements.yml to v2.0.10

**Comment by springdo** [comment]
Our preferred support route for the techie content is to use the CodeReadyWorkspaces provided by the Facilitators. We are removing any reliance on local env and will remove the pages from the facilitation guide too. 

🚀
