### ISSUE TITLE
Update applier to v2.0.10 to avoid Ansible 2.8 errors

### ISSUE THREAD

**Issue by pcarney8** [rht-labs/enablement-docs#338]

**Comment by oybed** [comment]
@pcarney8 this has already been done, and I believe all instances have been found/changed. List of PRs (already merged) below:

https://github.com/rht-labs/enablement-ci-cd/pull/20
https://github.com/rht-labs/enablement-ci-cd/pull/21
https://github.com/rht-labs/enablement-ci-cd/pull/22
https://github.com/rht-labs/enablement-ci-cd/pull/23
https://github.com/rht-labs/enablement-ci-cd/pull/24
https://github.com/rht-labs/enablement-ci-cd/pull/25
https://github.com/rht-labs/enablement-ci-cd/pull/26
https://github.com/RedHatTraining/rht-labs-ci-cd/pull/8
https://github.com/RedHatTraining/rht-labs-ci-cd/pull/9
https://github.com/RedHatTraining/rht-labs-ci-cd/pull/10
https://github.com/RedHatTraining/rht-labs-ci-cd/pull/11
https://github.com/RedHatTraining/rht-labs-ci-cd/pull/12
https://github.com/RedHatTraining/rht-labs-ci-cd/pull/13
https://github.com/RedHatTraining/rht-labs-ci-cd/pull/14

Please re-open with specifics on which ones may not have been fixed if anything was missed.

**Comment by springdo** [comment]
@oybed  - I don't think there was a need to update all those locations for the version bump. You only need to update `master`
In the exercises, you don't checkout the whole branch. Mostly you just bring individual files in from other branches so these ones can remain having the old version. 
Plus git knows the version bump in that file is a newer change so it will not overwrite it if you do merge those features in as per in exercise 4 when you bring in the `Jenkinsfile`  from a feature branch to master.

**Comment by oybed** [comment]
@springdo Yes, fully aware of all of that, but in general I think it's a bad idea to have these files in multiple branches as they can easily be out of sync and hence cause confusion. Let's chat in August around the structure of the branches and/or if this is the best approach. I'll open another issue for this.
