### ISSUE TITLE
Exercise 2, Step 4 `npm install` command spits out an error that it can't find Python2

### ISSUE THREAD

**Issue by pcarney8** [rht-labs/enablement-docs#339]
Windows users run `npm install` command spits out an error that it can't find Python2

Similar bug and fix here in the first comment:
https://github.com/JeremyEnglert/JointsWP/issues/317

**Comment by springdo** [comment]
As per other issue, we have prebaked the workspace with all the lovely needed ingredients so closing out. thanks!
