### ISSUE TITLE
Pushing to Git returning Error Code 403 fatal: HTTP request failed

### ISSUE THREAD

**Issue by srahilly** [rht-labs/enablement-docs#342]
In 1. The Manual Menace, Part 3, you set a username and email address and then push the current configuration as code to git

git push -u origin --all

In my case, the push failed with the error message

remote: You are not allowed to push code to this project.
fatal: unable to access The requested URL returned error: 403

I believe this is because I didn't have an account on Gitlab

The solution I used was

git remote set-url origin https://<USER_NAME>@<GIT_URL>.git
where <USER_NAME> is the lab username and <GIT_URL> is the URL copied from Gitlab
https://stackoverflow.com/questions/7438313/pushing-to-git-returning-error-code-403-fatal-http-request-failed

I was then prompted for the password for <USER_NAME> and the push, and following actions, worked

**Comment by springdo** [comment]
Cannot reproduce.
