### ISSUE TITLE
Rework the structure of how branches are used in technical exercises

### ISSUE THREAD

**Issue by oybed** [rht-labs/enablement-docs#346]
**Is your feature request related to a problem? Please describe.**
The way the branches are currently use in the technical exercises can cause confusion - especially since the same files (e.g.: requirements.yml) exists in multiple branches but the content may not be in sync. For people not familiar with git this is confusing and can distract from the actual purpose of the technical exercise.

**Describe the solution you'd like**
I believe this should be discussed as part of the team working on enhancements, but maybe consider a different approach to these branches - one solution could be to just keep the delta in the branches. 

**Describe alternatives you've considered**
See above

**Additional context**
See issue #338 some additional context

**Comment by springdo** [comment]
Hi @oybed 

Thanks for raising this issue. This is something we can discuss alright when we meet-up in August, I imagine that list we all have to cover will be large! 
I look forward to seeing your suggested implementation of just storing the delta and how we'd change the repo and instructions to this method. I've not seen this cause learners much concern myself, but  perhaps we should do some user testing and take a sample group to validate each approach with?

**Comment by oybed** [comment]
@springdo as mentioned in original write-up, this is a topic I'd like to see some discussion around with the team to see what kind of enhancement solution we can come up with.

**Comment by oybed** [comment]
Side-note: With the current approach of using multiple branches for the exercises, it also makes it harder to manage releases / tags. Something we may want to do - especially right now with the transition from v3.x to v4.x of OCP.
