### ISSUE TITLE
Define Target Outcomes for the residency

### ISSUE THREAD

**Issue by springdo** [rht-labs/enablement-docs#35]

**Comment by tdbeattie** [comment]
[Priority Sliders](https://github.com/rht-labs/enablement-docs/blob/master/kick-off/priority-sliders.jpg) from kick off call held on 03 April 2018.

**Comment by tdbeattie** [comment]
https://github.com/rht-labs/enablement-docs/blob/master/kick-off/target-outcomes.jpg
