### ISSUE TITLE
Feature Enhancement: Combine exercise 2 and 4

### ISSUE THREAD

**Issue by oybed** [rht-labs/enablement-docs#352]
**Is your feature request related to a problem? Please describe.**
A repeat feedback I have heard from both facilitators and participants is that exercise 2 is "not the way we do things" - everything is done with Jenkinsfile. However, I have also heard from less technical participants that they like how exercise 2 outlines the use of Jenkins and make them better understand the technology without diving into "scripting" (such as a groovy / Jenkinsfile). 

**Describe the solution you'd like**
I would like to suggest that we look to combine exercise 2 and 4 in a way that meets both of these needs - i.e.: allow less technical participants to learn the flow in a manner that doesn't get too deep from a technical perspective, but yet it meets the need of a the more technical people to feel that it accomplishes what it needs to do - in the correct way. 

**Describe alternatives you've considered**
Changing exercise 2 to minimize its time consumption and allow users to not get "hung up" on this being the "wrong way". 

**Additional context**
We could maybe even consider convert exercise 2 to more of a "mobbing tasks" whereas we can have participants follow-along as someone leads the exercise. Maybe we could have "check-points" along the way that reports to a dashboard to indicate when each participant is done/at a certain step in the exercise (allowing the facilitator to track that everybody are following along). 

With this, I'd like to open this for discussion to see if we can get some alignment around how we meet the demand and feedback received. 

@eformat @dmytri @springdo @makentenza @mtakane @tdbeattie @tylerauerbeck @mcanoy

**Comment by tdbeattie** [comment]
This is a great summary of the problem @oybed - thanks for capturing it so well.

Likewise, I have seen both needs and seen the feedback that suggests the "click your way to success" approach in Exercise 2 is not appropriate (and actually a little frustrating) for a highly technical audience. I've also seen customers who have never seen Jenkins (or similar tooling) and they found the UI steps helped them understand how pipelines are pieced together.

So, it would be great to keep flexibility in the product and let the participants choose the best path for them. 

Perhaps we introduce a JenkinsFile for Exercise 2 and some additional instructions saying something like:
"If your table mob group are already familiar with Jenkins pipeline please follow the JenkinsFile instructions. If your group would like to configure pipelines manually, please follow these steps..." and let the groups decide which route they want to take. Either way we the exercise should always encourage conversation about the value of pipelines.

**Comment by springdo** [comment]
🌮 🌮 🌮  done. 🚀 🤖 🥇 🌮 🌮 🌮
