### ISSUE TITLE
Add Deployment Strategies to CI/CD Slides/Exercise

### ISSUE THREAD

**Issue by gsampaio-rh** [rht-labs/enablement-docs#353]
**Is your feature request related to a problem? Please describe.**
As some of the participants are not familiar with deployments tools/strategies and we talk a lot about it as it's an important process in CI/CD/Change management would be a good addition to add this type of content to cover more about deployment strategies.

**Describe the solution you'd like**
I think it would be good to add Deployment Strategies (Recreate, Rolling, Blue/Green, Canary, Shadow, Feature Toggle) to the slides and maybe do different strategies for the Front-End and the Back-End during the exercises.

**Describe alternatives you've considered**
All teams do different deployment strategies and do a quick talk about it in front of everybody

**Comment by springdo** [comment]
@tylerauerbeck  is taking the reigns on the slides for this one. closing this in favour of the other issues open on this one
