### ISSUE TITLE
Update or delete Value Stream Mapping

### ISSUE THREAD

**Issue by wentzel** [rht-labs/enablement-docs#356]
Value stream mapping is mentioned in the same slide as Metrics based process mapping. However, except for one or two sentences there is nothing more about Value stream mapping. All the rest (including exercise) is about Metrics based process mapping. Either Value stream mapping should be completely taken away, or there needs to be examples (real life) and clear explanations of what it is, and possibly an exercise also.

**Comment by tdbeattie** [comment]
Thanks @wentzel - very good point and great feedback.

I tend to describe VSM in my voiceover (with an example). I would like to keep both this and MBPN in and explain the difference and agree we need some additional material for this.  To satisfy our Definition of Done, we need some slideware, an experiential exercise and a real world example.

**Comment by maryprovinciatto** [comment]
Fixed by https://github.com/rht-labs/enablement-docs/commit/9da7bbe3e1e5a1125015c4284e5b5d1f0ebab24d
