### ISSUE TITLE
Use dynamic vars for exercise 1

### ISSUE THREAD

**Issue by mcanoy** [rht-labs/enablement-docs#362]
**Is your feature request related to a problem? Please describe.**
In exercise 1 there are a few instances where the user needs to create parameters specific to his/her environment (<Your Name>-ci-cd) in multiple param files. This frequently will cause copy/paste issues or misnamed errors

**Describe the solution you'd like**
I'd like to use dynamic parameters in the apply.yml instead of multiple param files.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by tylerauerbeck** [comment]
Resolved.
