### ISSUE TITLE
Event Storming

### ISSUE THREAD

**Issue by tdbeattie** [rht-labs/enablement-docs#37]
Content to introduce the practice of Event Storming, how we use it and show some examples of real Event Storm artefacts.

We will pre-bake an Event Storm map for the ToDoList business processes. We will use this to communicate the scope of the application using the event storming notation. 

Perhaps some kind of group exercise or discussion to solidify learning.

**Comment by sherl0cks** [comment]
As a reference: https://www.youtube.com/watch?v=1i6QYvYhlYQ. May be good to steal parts of his slides.

**Comment by tdbeattie** [comment]
[ ] create content on Event Storming in Google Slides
[ ] create a pre-baked event storm for ToDoList
[ ] create group exercise and test it out 
[ ] collect real event storms and add to Google Slides
