### ISSUE TITLE
Metrics-based Process Mapping (MBPM)

### ISSUE THREAD

**Issue by tdbeattie** [rht-labs/enablement-docs#39]
Content to introduce the practice of Metric Based Process Mapping, how we use it and show some examples of real MBPM artefacts.

Facilitate (with some pre-baked material) a MBPM of the E2E process of feature request generated from business to code running and being used in production. Capture some metrics associated with traditional software development (i.e. before automation, IaC, etc.). Brainstorm improvements we can apply using our engineering practices steering towards the key practices we're going to use in the following exercises. Show how we use this to build backlog of activities.

[ ] create content on MBPM in Google Slides
[ ] create a pre-baked example to showcase MBPM
[ ] create group exercise and test it out 
[ ] collect real MBPMs and add to Google Slides

**Comment by sherl0cks** [comment]
perhaps start with:

- https://vimeo.com/149407030
- https://docs.google.com/presentation/d/1Ijkm2zMLMiJ4KS_evA4ufug0fOL01QOEsxBsZ89_EdA/edit#slide=id.gb6f3e2d2d_2_207 
- https://www.slideshare.net/KarenMartinGroup/vsmmbpmwhenyouoptforeach
