### ISSUE TITLE
Create Project

### ISSUE THREAD

**Issue by tdbeattie** [rht-labs/enablement-docs#40]
Sprint 1 Feature: 
Create learner-ci-cd, learner-dev, learner-test for each learner using the openshift applier. Guide learners by providing the templates.

Tasks
- [x] Add exercise instructions to repo
- [x] Add templates to the Enablement CI/CD repo
- [x] Peer review exercise for accuracy
- [ ] Add components to BIG PICTURE

**Comment by sherl0cks** [comment]
@tdbeattie can you clarify the purpose of this issue (and #41 #42 #43 ) that are all quite similar? Is this to create the slides / content to walk folks through this? If so, we need have an open issue to discuss #2 how OpenShift projects will be provisioned.

**Comment by springdo** [comment]
@sherl0cks when we start sprint planning this afternoon we'll flesh out each of the features with a list of subtasks. That might clear some of the confusion?

**Comment by springdo** [comment]
Keeping this issue - closing the https://github.com/rht-labs/enablement-docs/issues/4

**Comment by springdo** [comment]
https://github.com/rht-labs/enablement-docs/pull/112

**Comment by springdo** [comment]
BIG PICTURE stuff not done but PR has been mergé. @tdbeattie - I think we could create a top level task each sprint next time to do the emerging arch. Something for the retro I guesS?
