### ISSUE TITLE
Add Nexus

### ISSUE THREAD

**Issue by tdbeattie** [rht-labs/enablement-docs#41]
Sprint 1 Feature: 
Create Nexus server using templates from ci/cd for use as part of the pipeline

Tasks
- [x] Add exercise instructions to repo
- [x] Add templates to the Enablement CI/CD repo
- [x] Peer review exercise for accuracy
- [ ] Add components to BIG PICTURE

**Comment by springdo** [comment]
https://github.com/rht-labs/enablement-docs/pull/115
