### ISSUE TITLE
Add Git

### ISSUE THREAD

**Issue by tdbeattie** [rht-labs/enablement-docs#42]
Sprint 1 Feature: 
Add Git (Lab or Gogs?) to the ci-cd namespace for the learner. Use templates from CoP library as starting point. 

Tasks
- [x] Add exercise instructions to repo
- [x] Add templates to the Enablement CI/CD repo
- [x] Peer review exercise for accuracy
- [ ] Add components to BIG PICTURE

**Comment by springdo** [comment]
https://github.com/rht-labs/enablement-docs/pull/115
