### ISSUE TITLE
Create an index page with all the links for the slides

### ISSUE THREAD

**Issue by maryprovinciatto** [rht-labs/enablement-docs#421]

**Comment by tdbeattie** [comment]
MVP for this is to use Trello board:

https://trello.com/b/NAFvLREW/facilitaor-master-please-duplicate-this

**Comment by mtakane** [comment]
This is also kinda done somehow. When I render the slides now it takes me to a listing of all the html pages we have plus a few more.

I recommend closing this actually.

**Comment by tdbeattie** [comment]
I agree @mtakane - by renaming the chapter1 deck (which was default deck when rendering), we end up with an index page. Between that and the Trello board, I think we have a couple of good navigation options. Let's close.
