### ISSUE TITLE
Add Jenkins

### ISSUE THREAD

**Issue by tdbeattie** [rht-labs/enablement-docs#43]
Sprint 1 Feature: 
Create Jenkins instance using the s2i. Have learners add new plugin eg Blue Balls to the s2i prior to build to allow hands on experience. Create from template on labs or cop repo

Tasks
- [x] Add exercise instructions to repo
- [x] Add templates to the Enablement CI/CD repo
- [ ] Peer review exercise for accuracy
- [ ] Add components to BIG PICTURE

**Comment by springdo** [comment]
https://github.com/rht-labs/enablement-docs/pull/116
