### ISSUE TITLE
Create Pipeline - F/E (Dev and Master)

### ISSUE THREAD

**Issue by tdbeattie** [rht-labs/enablement-docs#45]
Sprint 1 Feature: 
Add pipeline for app checking out from develop and deploying to labs-dev environment. Add master checkout to endup with app in test environment, replaying the pipeline.

Tasks
- [x] Add exercise instructions to repo
- [x] Add build and deploy ocp template to the Enablement CI/CD repo
- [x] Peer review exercise for accuracy
- [ ] Add components to BIG PICTURE 
- [x] Pipeline to do standard build > bake > deploy for the app

**Comment by springdo** [comment]
https://github.com/rht-labs/enablement-docs/pull/119

**Comment by springdo** [comment]
PR for bulk of work done; waiting to do task 2 until @sherl0cks gets back to me with his new way of doing this. The pipeline is in place and documented etc. I've just not documented how I got the ocp templates in place for Jenkins to run

**Comment by sherl0cks** [comment]
@springdo are you version controlling the final product somewhere? It would be very helpful to read that content, as opposed to trying to recreate it from the docs. Likely useful for participants too . The spring boot guides are a good example of this. https://github.com/spring-guides/gs-spring-boot

**Comment by springdo** [comment]
@sherl0cks  - versioning is something that is on my mind; for the moment all the content is tracked as markdown in in the docs. You can see new versions of the content come to life when we merge master > gh-pages. My Plan is to tag the whole repo at the end of the sprint on Weds; and all supplemental repos with the same tag to keep them inline. I think it is worth creating a separate issue to track / agree how we version. 
What you think? Maybe we discuss breifly on call tomorrow?

**Comment by sherl0cks** [comment]
I'm interested in the inventory specifically. I unfortunately do not have time to parse these docs. I looked around and it appears that the content is going to landed in https://github.com/rht-labs/enablement-ci-cd?

**Comment by springdo** [comment]
ahh OK; yeah so for the inventory there are branches in that repo that correspond to the sections as they get introduced. For example; when a leaner starts doing the jenkins s2i stuff they checkout files in that branch to their copy of the enablement-ci-cd repop and progress it from there.

 I thought about adding shortcuts for learners to be able to jump sections; but it's lower on my priority list
