### ISSUE TITLE
Add Jenkins Slave

### ISSUE THREAD

**Issue by tdbeattie** [rht-labs/enablement-docs#46]
Sprint 1 Feature: 
Add a slave node for Jenkins to be able to execute builds in. Use the NodeJS one hosted on the CoP with Chrome installed already as will be used later. NOTE - this could be done as part of lab1 or lab2, figure out where it makes more sense to add when going through the material.

Tasks
- [x] Add exercise instructions to repo
- [x] Add build of slave from OCP template to the Enablement CI/CD repo
- [ ] Peer review exercise for accuracy
- [ ] Add components to BIG PICTURE

**Comment by springdo** [comment]
https://github.com/rht-labs/enablement-docs/pull/118
