### ISSUE TITLE
Create Pipeline - b/e API

### ISSUE THREAD

**Issue by tdbeattie** [rht-labs/enablement-docs#47]
Sprint 1 Feature: 
Add pipeline for app checking out from develop and deploying to learners dev environment. Add master checkout to endup with app in test environment, replaying the pipeline.

Tasks
- [x] Add exercise instructions to repo
- [x] Add build and deploy ocp template to the Enablement CI/CD repo
- [x] Peer review exercise for accuracy
- [ ] Add components to BIG PICTURE 
- [x] Pipeline to do standard build > bake > deploy for the app

**Comment by springdo** [comment]
https://github.com/rht-labs/enablement-docs/pull/120

**Comment by springdo** [comment]
Waiting on the other one about the build / deploy configs to be resolved first

**Comment by springdo** [comment]
missing part https://github.com/rht-labs/enablement-docs/pull/125
