### ISSUE TITLE
step 12 in manual menace refs. a playbook dir that doesn't exist

### ISSUE THREAD

**Issue by ChristinaMeno** [rht-labs/enablement-docs#475]
apply.yml is actually in the enablemet-ci-cd dir see 

.
├── README.md
├── apply.yml
├── docker
├── inventory
│   ├── group_vars
│   │   ├── all.yml
│   ├── host_vars
│   │   ├── ci-cd-tooling.yml
│   │   └── projects-and-policies.yml
│   └── hosts
├── jenkins-s2i
├── requirements.yml
└── templates
 └── project-requests.yml

**Comment by ChristinaMeno** [comment]
we worked around it by doing ansible-playbook apply.yml -i inventory/ -e target=bootstrap

**Comment by tylerauerbeck** [comment]
@ChristinaMeno Thanks for the issue! It looks like we've already resolved this in the docs, just may not have published the latest changes to Github pages. I'm going to capture some additional changes and then look to republish at the end of the day.
