### ISSUE TITLE
When changing the remote in attack of the pipelines the indentation is weird.

### ISSUE THREAD

**Issue by ChristinaMeno** [rht-labs/enablement-docs#478]
This kinda prevents me from reading the actual steps and I'm left wondering how to do this...

see screenshot 
<img width="1384" alt="Screen Shot 2019-08-07 at 1 55 49 PM" src="https://user-images.githubusercontent.com/290210/62646200-c0b73b00-b91b-11e9-9c03-b33b06af38fe.png">

**Comment by oybed** [comment]
Resolved by #489
