### ISSUE TITLE
Add MongoDB for each project

### ISSUE THREAD

**Issue by tdbeattie** [rht-labs/enablement-docs#48]
Sprint 1 Feature: 
Add mongodb setup for each project namespace. NOTE - need to figure out how to add it into the build as will be required by the tests in lab3

Tasks
- [x] Add exercise instructions to repo
- [x] Add build and deploy ocp template to the Enablement CI/CD repo
- [x] Peer review exercise for accuracy
- [ ] Add components to BIG PICTURE 
- [x] ensure app can connect to the db once running ie usernames etc captured in the docs

**Comment by springdo** [comment]
This work was completed as part of several other PRs as that was the only way it made sense in the flow. The final PR is this guy but it was tied to the work for BE and FE deploys too.

https://github.com/rht-labs/enablement-docs/pull/125
