### ISSUE TITLE
Jenkins slave unable to pull NPM image from local ${name}-ci-cd registry

### ISSUE THREAD

**Issue by paulbarfuss** [rht-labs/enablement-docs#481]
Currently DO500 classmates are running into an issue where the jenkins-slave-npm slave is unable to pull the docker image from `docker-registry.default.svc:5000/pbarfuss-ci-cd/jenkins-slave-npm`

The image exists in my project, however it is throwing a permissions error:

> you may not have access to the Docker image "openshift/jenkins-slave-npm:latest". Timestamp: 2019-08-07T14:18:16Z Error count: 2

My workaround was to change the Kubernetes Pod Template in https://${jenkins_url}/configure to point to `docker-registry.default.svc:5000/openshift/jenkins-slave-npm` to complete the exercise.

**Comment by tylerauerbeck** [comment]
The second workaround here was to just point the local imagestream to quay.io/rht-labs/enablement-npm:latest

**Comment by oybed** [comment]
The linkage from `<username>-ci-cd/jenkins-slave-npm` to `openshift/jenkins-slave-npm` is done by the 3rd section in the `ci-cd-builds` section (Exercise 1, Part 6, Step 8), and that should be the resolution to this issue. Maybe that portion of that inventory file was omitted / missed for those classmates that experienced this issue/

**Comment by paulbarfuss** [comment]
From what I am seeing, it appears that Jenkins can pull docker images from either quay.io or the cluster `openshift` project directly:
![jenkins-slave-npm](https://user-images.githubusercontent.com/18050645/62727724-13f6bf80-b9e8-11e9-9f30-f746a426b3ac.png)

There seems to be a permissions issue with the service account reaching across from the `<username>-ci-cd` over to the `openshift` project.

![jenkins-slave-npm-error](https://user-images.githubusercontent.com/18050645/62728386-acda0a80-b9e9-11e9-83c8-91a2e07adca0.png)

My working theory is we need to add `system:image-puller` to the service account. For the [docs](https://docs.openshift.com/container-platform/3.11/dev_guide/managing_images.html#using-image-pull-secrets), it might look something like the following:

```
oc policy add-role-to-group \
    system:image-puller system:serviceaccounts:<username>-ci-cd \
    --namespace=openshift
```

**Comment by oybed** [comment]
Thx for the additional info. I was able to reproduce this issue. Basically, the ImageStream is referencing the wrong type/image. I'll have a PR out for it soon.
