### ISSUE TITLE
Exercise 2, Part 4, Step 2: Update Jenkinsfile snippet

### ISSUE THREAD

**Issue by tylerauerbeck** [rht-labs/enablement-docs#485]
Jenkinsfile snippet references:

`GIT_CREDENTIALS = credentials('jenkins-git-creds')`

And should be:

`GIT_CREDENTIALS = credentials("${NAMESPACE_PREFIX}-ci-cd-gitlab-auth")`

**Comment by oybed** [comment]
Resolved by #489
