### ISSUE TITLE
Introduction to ToDoList App and local execution

### ISSUE THREAD

**Issue by tdbeattie** [rht-labs/enablement-docs#49]
Sprint 1 Feature: 
Introduce the ref app. Get building locally and running locally so learners can explore the app. Check app into git instance created in previous lab. 

Tasks
- [x] Add exercise instructions to repo
- [ ] Peer review exercise for accuracy
- [ ] Add components to BIG PICTURE 
- [ ] Overview of the stack and the vue's component architecture and vuex store

**Comment by springdo** [comment]
https://github.com/rht-labs/enablement-docs/pull/117
