### ISSUE TITLE
Attack of the pipelines - Part 2 - ansible galaxy path issues

### ISSUE THREAD

**Issue by Mint3kool** [rht-labs/enablement-docs#490]
* Problem numbering is inconsistent
* oc login should indicate which project to work from
* ansible-galaxy install path is wrong
  * should indicate that you need to be in .openshift-applier directory
  * should be: `ansible-galaxy install -r requirements.yml --roles-path=roles`

**Comment by oybed** [comment]
I believe this issue has been resolved with PR #512. Closing issue. Please re-open if you believe it's still an issue.
