### ISSUE TITLE
Jenkins URL is displaying GitLab in Chrome during Exercise 1

### ISSUE THREAD

**Issue by paulbarfuss** [rht-labs/enablement-docs#492]
This issue can be replicated by creating a new Freestyle Project in Jenkins:

![jenkins-gitlab1](https://user-images.githubusercontent.com/18050645/62784667-00e9fb00-ba8d-11e9-806c-75733920a78d.png)

Then paste the gitlab link into the Git SCM Source field:

![jenkins-gitlab2](https://user-images.githubusercontent.com/18050645/62784713-1828e880-ba8d-11e9-9eec-680d6eb2fea9.png)

It will attempt to open a login frame in the browser and subsequent page loads with the Jenkins URL will display GitLab pages:

![jenkins-gitlab3](https://user-images.githubusercontent.com/18050645/62784773-41497900-ba8d-11e9-9d5f-6d098631e76b.png)

**Comment by oybed** [comment]
I believe this is due to the browser cache and can be worked around by using for example incognito mode in Chrome.

**Comment by paulbarfuss** [comment]
Closing, this was most likely resolved by updating Jenkins and/or plugins.
