### ISSUE TITLE
Add convenience methods to package.json to stop backgrounded apps ie frontend or api

### ISSUE THREAD

**Issue by springdo** [rht-labs/enablement-docs#495]
**Is your feature request related to a problem? Please describe.**
When users close the browser tab, all the running in the fore terminal processes are backgrounded. This causes issues for people stopping / starting apps.

**Describe the solution you'd like**
create some helper functions for the app in the package.json that either kill the process' or bring them to the fore

**Describe alternatives you've considered**
Educate the learners how to stop start background process. Ie lots of pf -ef | grep node & kill -9

**Additional context**
this was chatted about in the feedback from Post boston pilot of course

cc @tylerauerbeck  from our convo yday

**Comment by springdo** [comment]
Other idea could be to use our good ol friend Screen 
https://www.rackaid.com/blog/linux-screen-tutorial-and-how-to/

**Comment by eformat** [comment]
```
killall node
```
also works ...

**Comment by springdo** [comment]
closing this for now as it will do with our killall solution
