### ISSUE TITLE
Exercise 3 - Revenge of the Automated Testing

### ISSUE THREAD

**Issue by springdo** [rht-labs/enablement-docs#5]
## Technical Lab
This is the Lab where a new feature will be built. We could update the Product Backlog created on Day 1 to reflect that some features have been built (we could say we’re fast forwarding to Sprint 2) and top priority item are the ones we’ve set in the Lab to create. The new feature would be built using TDD, and built as a single, fullstack feature. Probably a new flag on the todo list to mark an item as important

## Ideas for the Lab flow:
 * Introduce new feature and TDD
 * Add all tests to the pipeline and add E2E test phase after deploy
 * Git branch and implement tests to fail
 * Implement FE of feature to pass the tests (Jest or Mocha)
 * Implement Backend tests using Mocha / Chai
 * Implement API level feature and data model to pass the tests
 * Write feature e2e test.

## ADVANCED / XTRA TOPICS
 * Add more complex features to the app such as a user login using  auth0 as a service or Passport JS for local user dbs
 * Add Notification microservice for when TODOs are marked as done 
 * Add Blue/ Green deployment switch over based on E2E test scores

**Comment by sherl0cks** [comment]
Would like to discuss the method for introducing TDD
