### ISSUE TITLE
Add Tests and E2E to Pipeline

### ISSUE THREAD

**Issue by tdbeattie** [rht-labs/enablement-docs#51]
Sprint 1 Feature: 
Enhance pipeline with testing (unit etc) for each service (backend and front end). Add test reporting through jenkins. Fail build if tests fail thus removing our ungated pathway to production....

Tasks
- [x]  write doc for existing tests runing + reporting in Jenkins
- [ ]  actually write the e2e tests

**Comment by springdo** [comment]
Think this was a mistake to bring in now. It is the first part of the next exercise. If we have time to get to it I will try but in terms of the slice; it think we can get to having Lab 1 * 2 finished by Weds.

**Comment by springdo** [comment]
https://github.com/rht-labs/enablement-docs/pull/140 for the fe / be tests. end to end tests needs to be looked at.
