### ISSUE TITLE
Exercise 4 - Scaling and Slaves

### ISSUE THREAD

**Issue by springdo** [rht-labs/enablement-docs#6]
## Technical Lab
Extend jenkins with configuration as code for pipelines using DSL or Declarative-pipeline-as-code. Introduce new Slaves for Jenkins to consume in future builds. Add a helper job for re-deploying specific version of the app.

## Ideas for the Lab flow:
* Introduce Pipeline as code and why it’s important.
* Migrate existing jobs to DSL / Pipeline syntax
* Add new slaves to be used later for ZAP and Arachni Scanning
* Add helper jobs to Jenkins. 

## ADVANCED / XTRA TOPICS
* ??

**Comment by sherl0cks** [comment]
I don't understand this exercise and why it is different than #3 . IMHO -we should be working with Jenkinsfile and OpenShift sync plugin from the start. Let's discuss.

**Comment by springdo** [comment]
@sherl0cks  - cool, let me explain so... In my experience working with Jenkins and from teaching the course back in IBM days; those who are new to Jenkins are usually overwhelmed by it. People who are new to automation are often perplexed by not fully knowing what Jenkins is capable of or what they want to report / capture / how to run a build etc. By allowing people start in the safety of the UI, people destigmatize Jenkins and are more comfortable with advanced topics such as Pipeline as code etc. By having people click there way to success initially; they can build up to doing really awesome things.
