### ISSUE TITLE
Missing images

### ISSUE THREAD

**Issue by ewoks** [rht-labs/enablement-docs#618]
It seems like repo is missing some images, e.g. [event_storming.md](https://github.com/rht-labs/enablement-docs/blob/master/slides/markdown/event_storming.md)

**Comment by rmarting** [comment]
@ewoks The images are not displayed directly when you are browsing the Markdown documents. The images are avaiable when you start locally the server to serve the content, as it is described in the [README.md](https://github.com/rht-labs/enablement-docs/blob/master/slides/README.adoc) file.

IMHO this is not an issue itself. So we could close it.
