### ISSUE TITLE
Exercise 6 - Return of the App Monitoring

### ISSUE THREAD

**Issue by springdo** [rht-labs/enablement-docs#8]
## Technical Lab
Add application monitoring tooling such as Jenkins Dashboards and API Traffic Lights. Tighten the feedback loop by using Build Fail Analyser to suggest why builds have failed.

## Ideas for the Lab flow:
 * Use DSL to build TL jobs
 * Create app build monitors showing vital info such as committer and test scores.
 * Add regex for build fail analyser to allow fast feedback

## ADVANCED / XTRA TOPICS
 * Slack Notifications (WebHooks)
 * Hue Lights 
 * Twilliio messaging for build stats
 * ‘Say’ command for Jenkins to tell when the build fails 
 * Alexa “is the build passing?” skills

**Comment by sherl0cks** [comment]
@springdo I usually take app monitoring to mean something different, e.g. deploy time stuff. This is cool stuff, but I do not consider it vital for folks to learn at the enablement.
