### ISSUE TITLE
Write tests to use Stryker to automate mutation testing and reporting through Jenkins 

### ISSUE THREAD

**Issue by tdbeattie** [rht-labs/enablement-docs#90]

**Comment by acammies** [comment]
@tompage1994 Has just created a fantastic write-up of Stryker, would be great to get him involved!

**Comment by Tompage1994** [comment]
@springdo you closed this, but as we mentioned before it'd be good to get some kind of extension exercise in there once the vue-mutator (https://github.com/stryker-mutator/stryker/pull/723) has been added to the Stryker project. Perhaps you want to reopen this?

**Comment by springdo** [comment]
Updated the title, closed it as I thought the Video would do for the moment.

**Comment by springdo** [comment]
Closed as per comment above
