### ISSUE TITLE
Videos and Time Dividers

### ISSUE THREAD

**Issue by tdbeattie** [rht-labs/enablement-docs#96]
Plan to play some short, powerful videos we often used on residencies - e.g.

- Henrik Kniberg Product Ownership in a Nutshell
- Henrik Kniberg Bootstrapping an Agile Projects using CI/CD and Cloudbees
- Donal's Big Picture
- Dan Pink's What Motivates You - Autonomy, Mastery and Purpose

**Comment by tenfourty** [comment]
I really like agile memes on twitter - https://twitter.com/agile_memes

For example:
https://pbs.twimg.com/media/CzysGOZVQAAN3Y1.jpg:large

**Comment by valyonchev** [comment]
Here are some more on the fun side and not always relevant, but they can come useful to wake up people https://www.youtube.com/playlist?list=PLNnbClPHLb2l502oUWHJ8-tqjPi8Z6U1e

**Comment by valyonchev** [comment]
David Marquet, Turn the ship around - Self Organizing teams and the use of Impact Mapping as a way to build Clarity https://www.youtube.com/watch?v=OqmdLcyES_Q
